name: Push Build
on: push
jobs:
   deploy:
     runs-on: ubuntu-latest
     steps:
       - name: Get Code
         uses: actions/checkout@v4
       - name: Set up JDK 21 for x64
         uses: actions/setup-java@v4
         with:
           java-version: '21'
           distribution: 'temurin'
           architecture: x64
       - name: Run the Maven package phase
         run: mvn --batch-mode --update-snapshots package
       - name: Meldung anzeigen
         run: echo "Fertig!"