name: Push Build
on: push
jobs:
   deploy:
     runs-on: ubuntu-latest
     steps:
       - name: Get Code
         uses: actions/checkout@v4
       - name: Set up JDK 21 for x64
         uses: actions/setup-java@v4
         with:
           java-version: '21'
           distribution: 'temurin'
           architecture: x64
       - run: mvn --batch-mode --update-snapshots verify
                - run: mkdir staging && cp target/*.jar staging
                - uses: actions/upload-artifact@v4
                  with:
                    name: Package
                    path: staging
       - name: Meldung anzeigen
         run: echo "Fertig!"