name: Push Build
on: push
jobs:
   deploy:
     runs-on: ubuntu-latest
     steps:
       - name: Get Code
         uses: actions/checkout@v4
       - name: Set up JDK 21 for x64
         uses: actions/setup-java@v4
         with:
           java-version: '21'
           distribution: 'temurin'
           architecture: x64
       - name: Setup Oracle DB
         uses: gvenzl/setup-oracle-free@v1
         with:
             port: 1521
             oracle-password: 1234
             app-user: system
             app-user-password: 1234
       - run: mvn --batch-mode --update-snapshots verify
       - run: mkdir staging && cp target/*.jar staging
       - name: Upload
         uses: actions/upload-artifact@v4
         with:
            name: Package
            path: staging
       - name: Meldung anzeigen
         run: echo "Fertig!"