name: Push Build
on: push
jobs:
   deploy:
     runs-on: ubuntu-latest
     steps:
       - name: Get Code
         uses: actions/checkout@v4
       - name : Update Java
         run: apt-get update
       #- name: Set up JDK 21 for x64
       #  uses: actions/setup-java@v4
       #  with:
       #    java-version: '21'
       #    distribution: 'temurin'
       #    architecture: x64
       - name: Test Java Version
         run: echo $JAVA_HOME
       - name: Liquibase
         uses: liquibase/liquibase-github-action@v7
         with:
           operation: 'update'
           classpath: 'db/'
           changeLogFile: 'master.xml'
           username: 'dbuser'
           password: 'dbpass'
           url: 'jdbc:mysql://localhost/test'
       - name: MySQL Docker
         uses: mirromutth/mysql-action@v1.1
         with:
           mysql root password: 'dbpass' # Required if "mysql user" is empty, default is empty. The root superuser password
           mysql user: 'dbuser' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
           mysql password: 'dbpass' #${{ secrets.DatabasePassword }} # Required if "mysql user" exists. The password for the "mysql user"
       - run: mvn --batch-mode --update-snapshots verify
       - run: mkdir staging && cp target/*.jar staging
       - name: Upload
         uses: actions/upload-artifact@v4
         with:
            name: Package
            path: staging
       - name: Meldung anzeigen
         run: echo "Fertig!"