name: Push Build
on: push
jobs:
   deploy:
     runs-on: ubuntu-latest
     services:
       oracle:
         image: gvenzl/oracle-free:latest
         env:
           ORACLE_RANDOM_PASSWORD: true
           APP_USER: test
           APP_USER_PASSWORD: 1234
         ports:
           - 1521:1521
         options: >-
           --health-cmd healthcheck.sh
           --health-interval 10s
           --health-timeout 5s
           --health-retries 10
     steps:
       - name: Get Code
         uses: actions/checkout@v4
       - name: Set up JDK 21 for x64
         uses: actions/setup-java@v4
         with:
           java-version: '21'
           distribution: 'temurin'
           architecture: x64
       - name: Setup Oracle DB
         uses: gvenzl/setup-oracle-free@v1
       - run: echo "SELECT 'HUHU';" | sql test/1234@localhost/FREEEPDB1
       - run: mvn --batch-mode --update-snapshots verify
       - run: mkdir staging && cp target/*.jar staging
       - name: Upload
         uses: actions/upload-artifact@v4
         with:
            name: Package
            path: staging
       - name: Meldung anzeigen
         run: echo "Fertig!"